logbook:
  exclude:
    - /actuator/health/**
  format:
    style: http
  minimum-status: 400
  strategy: body-only-if-status-at-least

logging:
  level:
    root: warn
    service: info
    org.zalando.logbook: trace

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: when_authorized
      probes:
        enabled: true
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - info
          - health
          - metrics

server:
  shutdown: graceful

spring:
  application:
    name: spring-modulith-example
  datasource:
    url: "jdbc:postgresql://localhost:5432/database"
    username: "user"
    password: "password"
  jackson:
    default-property-inclusion: non_null
  modulith:
    default-async-termination: false
    events:
      jdbc:
        schema-initialization:
          enabled: true
    moments:
      enable-time-machine: false
      granularity: hours
      locale: de_DE
      quarter-start-month: january
      zone-id: Europe/Berlin
    republish-outstanding-events-on-restart: true

---
spring.config.activate.on-profile: json-logging

logbook:
  format:
    style: json

logging:
  config: classpath:logback-json.xml
